title: TechVidhi
description: Learn embedded, IoT, and real-time debugging like a pro.
baseurl: "/techvidhi.in"
url: "https://<VidhiVadher>.github.io"
theme: minima  # you can switch to a custom theme

